config/routes.rb
Quizapp::Application.routes.draw do
  get "exam/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users
   get "users/sign_up"
  get "users/sign_in"

  resources :questions

  get "quiz/index"

  post "quiz/start"

  get "quiz/question"

  post "quiz/question"

  post "quiz/answer"

  get "quiz/end"

  post "choices/create"

  post "choices/destroy"

root :to => "quiz#index"

   match ':controller(/:action(/:id))(.:format)'
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :text,:subject_id
  has_many :choices
  has_many :result, :through=>:user_answers
  has_one :user_answer
  belongs_to :subject
  #has_many :users, :through => :types
  #set_primary_key 'type'
  def answer
	 uncorrect
	 choices.select {|c| c.correct}[0]
  end	
  
  def uncorrect
	 choices.each {|c| c.correct = false}
  end
  
  def answer= choice
	 if !answer.nil?
		answer.correct = false
	 end
	 
	 if choices.include? choice
		choice.correct = true
	 else
		choices << choice
		choice.correct = true
	 end
  end
  def to_s
    text
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml
 #before_filter :authenticate_user!
  def index
    @questions = Question.all
    @questions.sort! {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/questions_helper.rb
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Author::    1165536 Juliana Pena

module QuestionsHelper
end

app/views/questions/_form.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.label :Programing_language,"Select Language" %>
<%=f.collection_select :subject_id, Subject.all , :id, :subject, :include_blank => false ,:autofocus => true %>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text, :size => "50x15" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  Edit Question
<% end %>

app/views/questions/index.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<h1>Listing questions</h1>

<p>Total: <%= @questions.size %></p>
<p><%= link_to 'New Question', new_question_path %></p>

<table border="1">
  <tr>
    <th>Text</th>
    <th>Choices</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.choices.each do |choice| %>
          <li>
            <%= choice.text %>
            <% if choice.correct %> (Correct) <% end %>
          </li>
        <% end %>
      </ul>
    </td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>



<% content_for(:title) do %>
  All Questions
<% end %>

app/views/questions/new.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  New Question
<% end %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>


  <b>Text:</b>
  <% @question.text.split("\n").each do |t| %>
  <%= t %><br>
<% end %>


<h4>Choices</h4>
<ul>
  <% @question.choices.each do |choice| %>
	 <li>
		<%= choice.text %>
		<% if choice.correct %> (Correct) <% end %>
		
		<%= form_tag({:controller => "choices", :action => "destroy"}) do %>
		  <%= hidden_field_tag :question, @question.id %>
		  <%= hidden_field_tag :choice, choice.id %>
		  <%= submit_tag "Delete" %>
		<% end %>
		
	 </li>
  <% end %>
</ul>

<h5>New Choice</h5>
<%= form_tag({:controller => "choices", :action => "create"}) do %>
  <%= hidden_field_tag :question, @question.id %>
  
  <%= label_tag :text, "Text" %><br />
  <%= text_field_tag :text %>
  <br />
  <%= check_box_tag :correct %>
  <%= label_tag :correct, "Correct" %>
  <br />
  <%= submit_tag "Create" %>
<% end %>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  Question Details
<% end %>